pull_request_rules:
  - name: Automatic merge when images are changed in the community upload dir.
    conditions:
      - files~=^(!?Community_Upload/)
      - base=main
    actions:
      merge:
        method: merge
