pull_request_rules:
  - name: Automatic merge when images are changed in the community_upload dir.
    conditions:
      - and:
          - files~=^(!?Community_Upload/)
          - base=main
          - or:
              - files~=.png
              - files~=.jpeg
              - files~=.jpg
    actions:
      merge:
        method: merge
